### PR TITLE
Update ONBOARDING.md

### PR DESCRIPTION
**Pull request by rbeyer**
Wanted to capture these PR policies somewhere other than the meeting notes.

### CODE REVIEW

**Comment by jessemapel** [comment]
I think this is better documented on the README https://github.com/planetarysoftware/TSC#policy-change-proposal-process

**Comment by rbeyer** [comment]
Yeah, I didn't really see a natural place in the README for this.  The README seemed to be dealing with things at a high level, and this seemed like a more functional issue.  Where would you put it in the README?

**Comment by jessemapel** [comment]
The last section of the README titled ***Policy Change Proposal Process*** covers how changes to policy documents are done. That seems like the obvious place to put this.

**Comment by rbeyer** [comment]
Okay, I tried out a change on the main README in #46.  If we like that, I can abandon this.

**Comment by rbeyer** [comment]
We went with #46 as a solution, so this PR is no longer needed.

**Pull request closed without merging**
