### PR TITLE
Added the PlanetaryPy project pursuant to vote in meeting.

### PR DESCRIPTION
**Pull request by rbeyer**

### CODE REVIEW

**Comment by rbeyer** [comment]
Would close #108 and #112

**Review by jessemapel — APPROVED** [review]
👍

**Comment by rbeyer** [comment]
Doesn't this need two approvals?  I agree that it seems like a foregone conclusion, but ...

**Comment by jessemapel** [comment]
I assumed that this was good to go since we already voted in the meeting on it?

**Comment by rbeyer** [comment]
Agreed.  However, [CONTRIBUTING.md](https://github.com/planetarysoftware/TSC/blob/master/Contributing.md) says 24 h and two approvals.  The rules on [graduation votes](https://github.com/planetarysoftware/TSC/blob/master/Lifecycle.md#6-tsc-graduation-vote) say that the PR must either be approved by a majority (if not discussed at a meeting) or undergo the "regular" process (24 h and 2 approvals) if it was.  I feel like we need to follow our own rules if we expect anyone else to.

**Pull request merged**
