### PR TITLE
LPSC2020 abstract text

### PR DESCRIPTION
**Pull request by rbeyer**
Added our names in alpha order and copy'n'pasted the README.  Not sure what else to put in here...

### CODE REVIEW

**Comment by AndrewAnnex** [comment]
I think we can outline what we want to say in the issue discussion, these can all be one or more paragraphs
1. What is the TSC
a. what inspired it, why they made one, roles, etc
2. Why do we think planetary science needs the TSC
a. how we think it can help, what issues we are addressing, etc 
3. How does the TSC work
a. summarize the governance docs, talk about github, meetings etc
4. How to participate in the TSC
a. talk github, encourage discussion with TSC, etc
I am frantically trying to finish my other abstract so I may have time to more directly write things tonight/tomorrow.
also @rbeyer, maybe to make faster progress just make a new branch and we can directly merge into that branch instead of PRing each text contribution? we could move my text above to an issue.

**Comment by rbeyer** [comment]
Sure, so this PR is coming from the ``lpsc2020`` branch on our repo.  Let's try an expedited model, shall we: I hereby give permission for anyone to push directly to this branch, please continue to discuss via this PR and once we feel like it is 'ready to go' we will note it in the PR comments, and explicitly reguest review and merging.

**Comment by rbeyer** [comment]
Looks like not a lot of people have time to work on this (which was entirely expected).  If we don't get something more substantial, we can pass on LPSC, and aim for an abstract at PSIDA.

**Comment by michaelaye** [comment]
yeah, sorry, am late on mine as well, following a crazy idea of super-resolution data reconstruction...

**Comment by AndrewAnnex** [comment]
yeah I would contribute more but I am pretty worn out from my other work

**Comment by jessemapel** [comment]
Having just finished an abstract, I don't have time to contribute more here. PSIDA sounds like a good choice.

**Comment by victoronline** [comment]
Same. I don't expect to have time until next week. Sorry All.

**Pull request merged**
