### PR TITLE
Fix broken links in Projects.md

### PR DESCRIPTION
**Pull request by krlberry**
Fix broken links in Projects.md

### CODE REVIEW

**Comment by rbeyer** [comment]
The problem with these links isn't the shape of the brackets, but the capitalization of 'Lifecycle' I think.

**Review by michaelaye — CHANGES_REQUESTED** [review]
This isn't valid Markdown. The link should be 

`[lifecycle process](Lifecycle.md)`

I believe?

Edit: Confirmed. Above works (interestingly, not within this PR, I guess b/c we are down in the directory structure)

**Review by michaelaye — APPROVED** [review]

**Comment by michaelaye** [comment]
Anybody finds it odd that I can self-approve changes I made??

**Comment by rbeyer** [comment]
No, its possible given how GitHub works, but does violate our 'social contract' for how PRs work, although I can't find anywhere that we've written it down, so that's on us, I guess.

In general, unless someone says otherwise, you shouldn't push commits to someone else's PR.  They should take your comments, make the changes to the PR themselves, and then resolve the conversation.  Then it is okay for *you* to approve the PR that *they* have written.

**Comment by rbeyer** [comment]
However, since this PR is a 'typo fix' anyway, the fastest route to getting it fixed is probably the way to go, and not get hung up on procedure.

**Review by rbeyer — APPROVED** [review]

**Comment by krlberry** [comment]
I updated the links in this way because it seemed to match the way they'd previously been written, using reference-style links. See:  https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet (control-f reference style link.)

**Comment by michaelaye** [comment]
Ah sorry. I thought it's okay to update other's PR's but we said the final merge should be done by the original author?

**Comment by michaelaye** [comment]
Wow, I never saw double [][], didn't know that was a thing, sorry! What is the difference to the above link to google using the standard []()?

**Comment by rbeyer** [comment]
> I updated the links in this way because it seemed to match the way they'd previously been written, using reference-style links. See: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet (control-F reference style link.)

I have found links to be subtle in Markdown.  For 'reference style' links, you are relying on GitHub to perform a kind of search in the repo to find something that might match the word or phrase that you put in the second set of square brackets, kind of wiki-style.  However, in this case, we know exactly which filename in the repo we want this link to point to, and so we should use the style in the next example on that page: the "relative reference to a repository file".

**Comment by krlberry** [comment]
@rbeyer Updating to link directly to the markdown file (@michaelaye 's update) sounds good to me! (Though in this case, the line defining the reference link should probably be removed.) Just wanted to explain why I initially did the fix this way -- I was trying to make the most minimal possible change because I'm not on this repo/project, noticed the broken link when following the link to Projects.md over from the ISIS TC agenda PR, and this document was already using reference links so I just updated the brackets so that the existing reference-style link would function.

**Comment by michaelaye** [comment]
I'll be damned, I don't understand how [lifecycle process][lifecycle] can actually work if it's nowhere defined (like in .rst links) what [lifecycle] actually is? Does the GH Markdown parser really search for any potential match??

**Comment by michaelaye** [comment]
Ah sorry, it works via definition lines like in .rst files, didn't see that line in above changeset.

**Review by jessemapel — APPROVED** [review]

**Comment by rbeyer** [comment]
@kberryUSGS thank you so much for trying to help us fix this document.  You've also allowed @michaelaye and I to review what we thought we knew about Markdown links.

I was wrong, first time around.  The existing file has a []() link that points down to the reference line at the bottom of the Markdown file.  I *think* what was happening, is that GitHub wasn't properly resolving "Lifecycle.md" in that link, and might have worked if that line was "./Lifecycle.md".

So I think that might also have been a valid change that would achieved the same end as removing the reference link at the bottom and explicitly putting the link in at each occurrence, as the current PR is.

**Comment by michaelaye** [comment]
yeah, i will remember now that longer documents with lots of links also have the ability to refer to later definitions of the link. Thought only .rst can do that. Thanks, Kristin!

**Pull request merged**
